[package]
name = "esm-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hubcaps = { git = "https://github.com/softprops/hubcaps", branch = "master" }
serde_json = "1.0.73"
tokio = { version = "1.15.0", features = ["full"] }
